# site name
prefixName: 
siteName: 冬のせかい
# favicon and site master avatar
favicon: /WA2.ico
avatar: /kirito1.jpg
url: http://www.sisicheng.com/
root: /
description: Winter is coming ...
cdn: https://www.sisicheng.com/cdn
pjax: 1
# 1开启
mathjax: 0

notice:
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  分类: { path: javascript:;, fa: fa-sitemap faa-shake, submenus: { 
    戏言: {path: /categories/戏言/, fa: fa-ravelry}, 
    男子大学生の日常: {path: /categories/男子大学生の日常/, fa: fa-user-circle-o }, 
    砂糖实验室: {path: /categories/砂糖实验室/, fa: fa-flask}, 
    影视: {path: /categories/影视/, fa: fa-film}
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    番组: {path: /bangumi/, fa: fa-heart }, 
    歌单: {path: /music/, fa: fa-headphones },
  } }
  时间线: {path: /archives, fa: fa-calendar-check-o faa-shake}
  画廊: { path: /hualang/, fa: fa-picture-o }
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  # # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  #   我？: {path: /about/, fa: fa-meetup}, 
  #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #   Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bgn: 1

bg:
  - https://www.sisicheng.com/cdn/main-cover/(1).PNG
  - https://www.sisicheng.com/cdn/main-cover/(2).JPG
  - https://www.sisicheng.com/cdn/main-cover/(3).jpg
  - https://www.sisicheng.com/cdn/main-cover/(4).PNG
  - https://www.sisicheng.com/cdn/main-cover/(5).png
  - https://www.sisicheng.com/cdn/main-cover/(6).PNG

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# # startdash url, title, desc img
startdash: 
  - {url: https://www.hojun.cn/2019/02/20/cknemlo4n006luwtuaq85f0x1/, title: Sakura, desc: 本站 hexo 主题, img: /main-cover/sakura-theme.jpeg}
  - {url: https://space.bilibili.com/148095158, title: Bilibili, desc: 我的b站, img: /main-cover/bilibili.jpeg}
  - {url: /, title: 主页, desc: 最主的主页2333, img: /main-cover/home.png}



# your site build time or founded date
siteBuildingTime: 01/21/2020

#social  url, img PC端配置
# social:
#   github: {url: http://github.com/Molv1659, img: /social/github.png}
#   sina: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/sina.png}
#   wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wangyiyun.png}
#   zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/zhihu.png}
#   email: {url: http://weibo.com/mashirozx?is_all=1, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg}
#   wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png}
#   wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/Molv1659, fa: fa-github, color: 333}
#   weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
#   qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

# donate:
#   paypal: https://www.paypal.me/hojuncn
#   alipay: /img/custom/donate/AliPayQR.jpg
#   wechat: /img/custom/donate/WeChanQR.jpg
#   wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://www.sisicheng.com/cdn
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: violetCM.mp4

aplayer: 
  id: 2760714614
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true
  mini: true

# Valine
valine: true
v_appId: FpmoJ9C0hDlLHEIVqcHCTSo4-gzGzoHsz
v_appKey: hKq1YUOQGJvqrvQnT63ldkR6

# Waline
waline:
  enable: false
  serverURL: #服务端地址
  visitor: false #统计阅读量
  comment_count: true #统计评论数
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 祝开开心心！ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画